### ISSUE TITLE
Typo in the "about" section of the repo

### ISSUE THREAD

**Issue by Jazerus** [RetroAchievements/guides#7]
A while ago I fixed a typo in the readme.md, changing "A repo/wiki **to** achievement developers put guides for their achievement sets" to "A repo/wiki **for** achievement developers **to** put guides for their achievement sets". However, the ungrammatical original sentence remains in the about section of the repo and is what people see as a description when RAguides are embedded in Discord and the like. If there's a way to issue pull requests for the about section I don't know of it so I'm opening an issue instead.

**Comment by televandalist** [comment]
https://github.com/RetroAchievements/guides/pull/8

I rewrote it since anyone can write guides for any set, not just achievement developers for their own sets.

`A repo/wiki for RetroAchievement uaers to create guides for achievement sets.`

**Comment by SuperGamer18** [comment]
@televandalist the issue still exists in the "About" section itself and I don't think I can modify that...

**Comment by wescopeland** [comment]
Resolved

**Comment by SuperGamer18** [comment]
Cool, feel free to close this issue
